module.exports = {
  TEXT: {
    BEARER: "Bearer",
    ALGORITHM: "HS256",
  },
  TABLE: {
    LOGIN: "login",
    AUTH_SESSION: "auth_session",
    AUTH_REFRESH_TOKEN: "auth_refresh_token",
    AUTH_EVENT: "auth_event",
    CATEGORIES: "categories",
    SUB_CATEGORIES: "sub_categories",
    BRANDS: "brands",
    SUPPLIER: "supplier",
    SOURCE: "source",
    PRODUCT: "product",
    WAREHOUSE: "warehouse",
    AISLE: "aisle",
    PURCHASE: "purchase",
    PURCHASE_DETAILS: "purchase_details",
    COST_BUDGET: "cost_budget",
    INVENTORY: "inventory",
    PRODUCT_STATS: "product_stats",
    // Order spine (renamed from sales/sales_details). SALES/SALE_DETAILS keys are
    // kept as aliases so legacy controllers resolve to the renamed tables.
    ORDERS: "orders",
    ORDER_ITEMS: "order_items",
    SALES: "orders",
    SALE_DETAILS: "order_items",
    CUSTOMERS: "customers",
    CUSTOMER_ADDRESS: "customer_address",
    ONLINE_ORDER: "online_order",
    ORDER_SOURCE: "order_source",
    MESSAGE_TEMPLATE: "message_template",
    COURIER_CHECK: "courier_check",
    GIVEAWAY: "giveaway",
    GIVEAWAY_LINE: "giveaway_line",
    DIVISION: "division",
    DISTRICT: "district",
    THANA: "thana",
    POST_OFFICE: "post_office",
    AREA: "area",
    LOCATION_ALIAS: "location_alias",
    STOCK_HOLD: "stock_hold",
    STOCK_MOVEMENT: "stock_movement",
    STOCK_ADJUSTMENT: "stock_adjustment",
    STOCK_ADJUSTMENT_LINE: "stock_adjustment_line",
    ORDER_STATUS_HISTORY: "order_status_history",
    // Pre-order: a booking for stock not yet held. Deliberately NOT the orders
    // spine -- a pre-order is part of the sales process but is neither a sale
    // nor an order until it is converted.
    PRE_ORDERS: "pre_orders",
    PRE_ORDER_ITEMS: "pre_order_items",
    PRE_ORDER_STATUS_HISTORY: "pre_order_status_history",
    PRODUCT_RETURN: "product_return",
    RETURN_DETAILS: "return_details",
    PRODUCT_DISPOSE: "product_dispose",
    DISPOSE_DETAILS: "dispose_details",
    OTP_LOG: "otp_log",
    REQUEST_THROTTLE: "request_throttle",
    ROLE: "role",
    PERMISSION: "permission",
    ROLE_PERMISSION: "role_permission",
    MENU_ITEM: "menu_item",
    CONFIG_VERSION: "config_version",
    USER_NOTES: "user_notes",
    ACTIVITY_LOG: "activity_log",
    API_REQUEST_LOG: "api_request_log",
    SETTINGS: "settings",
  },
  CONTEXTS: {
    AUTH: "/api/v1/auth",
    ADMIN: "/api/v1/admin",
    PROFILE: "/api/v1/profile",
    CONFIGURATION: "/api/v1/configuration",
    INVENTORY: "/api/v1/inventory",
    ACTIVITY_LOG: "/api/v1/activity-log",
    SALES: "/api/v1/sales",
  },
  SUB_CONTEXTS: {
    USER: "/user",
    CATEGORY: "/category",
    SUB_CATEGORY: "/sub-category",
    BRANDS: "/brands",
    SUPPLIER: "/supplier",
    SUPPLIER_DEALER: "/supplier-dealer",
    PRODUCT: "/product",
    WAREHOUSE: "/warehouse",
    AISLE: "/aisle",
    ANALYTICS: "/analytics",
    SETTINGS: "/settings",
    PURCHASE: "/purchase",
    PURCHASE_ORDER: "/purchase-order",
    INVENTORY_OVERVIEW: "/inventory-overview",
    STOCK_MOVEMENT: "/stock-movement",
    STOCK_ADJUSTMENT: "/stock-adjustment",
    // Sales & Orders module (revamp)
    POS: "/pos",
    ONLINE: "/online",
    ORDER: "/order",
    ORDER_HISTORY: "/order-history",
    PRE_ORDER: "/pre-order",
    // Customer returns against a realized order. Mounted under SALES, not
    // INVENTORY: a return is rooted in an order (product_return.order_oid) and
    // the refund is sales money.
    RETURN: "/return",
    CUSTOMER: "/customer",
    LOCATION: "/location",
    PRODUCT_DISPOSE: "/product-dispose",
    CHANGE_PASSWORD: "/change-password",
    PROFILE_INFO: "/profile-info",
    NOTES: "/notes",
  },
  ROUTES: {
    SIGN_IN: "/sign-in",
    SIGN_OUT: "/sign-out",
    SIGN_OUT_EVERYWHERE: "/sign-out-everywhere",
    GET_SESSIONS: "/get-sessions",
    SIGN_OUT_SESSION: "/sign-out-session",
    REFRESH_TOKEN: "/refresh-token",
    GET_USER_INFO: "/get-user-info",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    GET_USER_LIST: "/get-user-list",
    CREATE_USER: "/create-user",
    UPDATE_USER_DETAILS: "/update-user-details",
    GET_USER_DETAILS: "/get-user-details",
    GET_USER_CARD: "/get-user-card",

    GET_CATEGORY_LIST: "/get-category-list",
    CREATE_CATEGORY: "/create-category",
    UPDATE_CATEGORY_DETAILS: "/update-category-details",
    GET_CATEGORY_DETAILS: "/get-category-details",
    GET_CATEGORY_LIST_FOR_DROPDOWN: "/get-category-list-for-dropdown",
    CHECK_CATEGORY_AVAILABILITY: "/check-category-availability",
    GENERATE_CATEGORY_CODE: "/generate-category-code",
    GENERATE_PRODUCT_LIST_REPORT_BY_CATEGORY:
      "/generate-product-list-report-by-category",
    GENERATE_INVENTORY_REPORT_BY_CATEGORY:
      "/generate-inventory-report-by-category",

    GET_SUB_CATEGORY_LIST: "/get-sub-category-list",
    CREATE_SUB_CATEGORY: "/create-sub-category",
    UPDATE_SUB_CATEGORY_DETAILS: "/update-sub-category-details",
    GET_SUB_CATEGORY_DETAILS: "/get-sub-category-details",
    GET_SUB_CATEGORY_LIST_FOR_DROPDOWN: "/get-sub-category-list-for-dropdown",
    CHECK_SUB_CATEGORY_AVAILABILITY: "/check-sub-category-availability",
    GENERATE_SUB_CATEGORY_CODE: "/generate-sub-category-code",
    GENERATE_PRODUCT_LIST_REPORT_BY_SUB_CATEGORY:
      "/generate-product-list-report-by-sub-category",
    GENERATE_INVENTORY_REPORT_BY_SUB_CATEGORY:
      "/generate-inventory-report-by-sub-category",

    GET_BRANDS_LIST: "/get-brand-list",
    CREATE_BRANDS: "/create-brand",
    UPDATE_BRANDS_DETAILS: "/update-brand-details",
    GET_BRANDS_DETAILS: "/get-brand-details",
    GET_BRANDS_LIST_FOR_DROPDOWN: "/get-brand-list-for-dropdown",
    CHECK_BRAND_AVAILABILITY: "/check-brand-availability",
    GENERATE_PRODUCT_LIST_REPORT_BY_BRAND:
      "/generate-product-list-report-by-brand",
    GENERATE_INVENTORY_REPORT_BY_BRAND: "/generate-inventory-report-by-brand",

    GET_SUPPLIER_LIST: "/get-supplier-list",
    CREATE_SUPPLIER: "/create-supplier",
    UPDATE_SUPPLIER_DETAILS: "/update-supplier-details",
    GET_SUPPLIER_DETAILS: "/get-supplier-details",
    GET_SUPPLIER_LIST_FOR_DROPDOWN: "/get-supplier-list-for-dropdown",
    GENERATE_SUPPLIER_PERFORMANCE_REPORT:
      "/generate-supplier-performance-report",
    EXPORT_SUPPLIER_DATA: "/export-supplier-data",
    CHECK_SUPPLIER_AVAILABILITY: "/check-supplier-availability",

    GET_SUPPLIER_DEALER_LIST: "/get-supplier-dealer-list",
    CREATE_SUPPLIER_DEALER: "/create-supplier-dealer",
    UPDATE_SUPPLIER_DEALER_DETAILS: "/update-supplier-dealer-details",
    GET_SUPPLIER_DEALER_DETAILS: "/get-supplier-dealer-details",
    GET_SUPPLIER_DEALER_LIST_FOR_DROPDOWN:
      "/get-supplier-dealer-list-for-dropdown",

    GET_PRODUCT_LIST: "/get-product-list",
    CREATE_PRODUCT: "/create-product",
    UPDATE_PRODUCT_DETAILS: "/update-product-details",
    GET_PRODUCT_DETAILS: "/get-product-details",
    GET_PRODUCT_LIST_FOR_DROPDOWN: "/get-product-list-for-dropdown",
    DELETE_PRODUCT: "/delete-product",
    CHECK_PRODUCT_AVAILABILITY: "/check-product-availability",
    GENERATE_PRODUCT_SKU: "/generate-product-sku",
    SIGN_PRODUCT_PHOTO_UPLOAD: "/sign-product-photo-upload",
    GENERATE_PRODUCT_INVENTORY_REPORT: "/generate-product-inventory-report",
    GENERATE_PRODUCT_MOVEMENT_REPORT: "/generate-product-movement-report",

    GET_WAREHOUSE_LIST: "/get-warehouse-list",
    CREATE_WAREHOUSE: "/create-warehouse",
    UPDATE_WAREHOUSE_DETAILS: "/update-warehouse-details",
    GET_WAREHOUSE_DETAILS: "/get-warehouse-details",
    GET_WAREHOUSE_LIST_FOR_DROPDOWN: "/get-warehouse-list-for-dropdown",
    CHECK_WAREHOUSE_AVAILABILITY: "/check-warehouse-availability",
    GENERATE_WAREHOUSE_CODE: "/generate-warehouse-code",
    GENERATE_PRODUCT_LIST_REPORT_BY_WAREHOUSE:
      "/generate-product-list-report-by-warehouse",
    GENERATE_INVENTORY_REPORT_BY_WAREHOUSE:
      "/generate-inventory-report-by-warehouse",

    GET_AISLE_LIST: "/get-aisle-list",
    CREATE_AISLE: "/create-aisle",
    UPDATE_AISLE_DETAILS: "/update-aisle-details",
    GET_AISLE_DETAILS: "/get-aisle-details",
    GET_AISLE_LIST_FOR_DROPDOWN: "/get-aisle-list-for-dropdown",
    CHECK_AISLE_AVAILABILITY: "/check-aisle-availability",
    GENERATE_AISLE_CODE: "/generate-aisle-code",
    GENERATE_PRODUCT_LIST_REPORT_BY_AISLE:
      "/generate-product-list-report-by-aisle",
    GENERATE_INVENTORY_REPORT_BY_AISLE: "/generate-inventory-report-by-aisle",

    GET_PURCHASE_LIST: "/get-purchase-list",
    CREATE_PURCHASE: "/create-purchase",
    UPDATE_PURCHASE_DETAILS: "/update-purchase-details",
    GET_PURCHASE_DETAILS: "/get-purchase-details",
    GET_PURCHASE_LIST_FOR_DROPDOWN: "/get-purchase-list-for-dropdown",
    VERIFY_PURCHASE: "/verify-purchase",
    UPDATE_BATCH_EXPIRY: "/update-batch-expiry",
    CANCEL_PURCHASE: "/cancel-purchase",
    UPDATE_PURCHASE_PAYMENT: "/update-purchase-payment",
    GET_PRODUCT_LIST_FOR_PURCHASE: "/get-product-list-for-purchase",

    GET_STOCK_OVERVIEW_LIST: "/get-stock-overview-list",
    GET_PRODUCT_STOCK: "/get-product-stock",
    GENERATE_PRODUCT_STOCK_REPORT: "/generate-product-stock-report",
    UPDATE_BATCH_PRICING: "/update-batch-pricing",
    UPDATE_BATCH_BUDGET: "/update-batch-budget",

    // --- Sales & Orders module (revamp; POS + online on the `orders` spine) ---
    GET_POS_PRODUCT_LIST: "/get-product-list",
    CHECKOUT_POS_SALE: "/checkout",
    PARK_POS_CART: "/park-cart",
    GET_PARKED_CARTS: "/get-parked-carts",
    DISCARD_PARKED_CART: "/discard-parked-cart",
    GET_ORDER_LIST: "/get-order-list",
    GET_ORDER_DETAILS: "/get-order-details",
    // Online order page
    GET_ONLINE_ORDER_SETUP: "/get-online-order-setup",
    READ_CHAT_MESSAGE: "/read-chat-message",
    CREATE_ONLINE_ORDER: "/create-online-order",
    SAVE_ONLINE_DRAFT: "/save-online-draft",
    GET_ONLINE_DRAFTS: "/get-online-drafts",
    DISCARD_ONLINE_DRAFT: "/discard-online-draft",
    // Orders list and record page
    CONFIRM_ORDER: "/confirm-order",
    CANCEL_ORDER: "/cancel-order",
    MARK_ORDER_PACKED: "/mark-order-packed",
    DISPATCH_ORDER: "/dispatch-order",
    DELIVER_ORDER: "/deliver-order",
    MARK_ORDER_NOT_DELIVERED: "/mark-order-not-delivered",

    // --- Returns feature (own router under /api/v1/sales/return) ---
    CREATE_RETURN: "/create-return",
    CONFIRM_RETURN: "/confirm-return",
    CANCEL_RETURN: "/cancel-return",
    MARK_RETURN_REFUNDED: "/mark-refunded",
    GET_RETURN_LIST: "/get-return-list",
    GET_RETURN_LIST_KPIS: "/get-return-list-kpis",
    GET_RETURN_DETAILS: "/get-return-details",
    GET_RETURNS_FOR_ORDER: "/get-returns-for-order",

    // --- Pre-Order feature (own tables; never the `orders` spine) ---
    GET_PRE_ORDER_LIST: "/get-pre-order-list",
    GET_PRE_ORDER_LIST_KPIS: "/get-pre-order-list-kpis",
    GET_PRE_ORDER_DETAILS: "/get-pre-order-details",
    CREATE_PRE_ORDER: "/create-pre-order",
    UPDATE_PRE_ORDER_DETAILS: "/update-pre-order-details",
    CONFIRM_PRE_ORDER: "/confirm-pre-order",
    CANCEL_PRE_ORDER: "/cancel-pre-order",
    RECORD_PRE_ORDER_ADVANCE: "/record-advance",
    GET_PRE_ORDER_NUMBER: "/get-pre-order-number",
    GET_PRE_ORDER_STOCK_READINESS: "/get-stock-readiness",
    GET_BATCHES_FOR_PRODUCT: "/get-batches-for-product",
    MARK_PRE_ORDER_CONVERTED: "/mark-converted",
    GET_PRE_ORDERS_BY_PRODUCT: "/get-pre-orders-by-product",
    GET_READY_TO_CONVERT: "/get-ready-to-convert",
    GET_PRODUCT_LIST_FOR_PRE_ORDER: "/get-product-list-for-pre-order",
    GENERATE_PRE_ORDER_REPORT: "/generate-pre-order-report",
    EXPORT_PRE_ORDER_DATA: "/export-pre-order-data",

    GET_PRODUCT_DISPOSE_LIST: "/get-product-dispose-list",
    CREATE_PRODUCT_DISPOSE: "/create-product-dispose",
    UPDATE_PRODUCT_DISPOSE: "/update-product-dispose",
    GET_PRODUCT_DISPOSE_DETAILS: "/get-product-dispose-details",
    APPROVE_PRODUCT_DISPOSE: "/approve-product-dispose",
    REJECT_PRODUCT_DISPOSE: "/reject-product-dispose",
    CANCEL_PRODUCT_DISPOSE: "/cancel-product-dispose",
    GENERATE_PRODUCT_DISPOSE_REPORT: "/generate-product-dispose-report",
    GET_PRODUCT_LIST_FOR_DISPOSE: "/get-product-list-for-dispose",
    GET_STOCK_MOVEMENT_LIST: "/get-stock-movement-list",
    GET_STOCK_ADJUSTMENT_LIST: "/get-stock-adjustment-list",
    GET_STOCK_ADJUSTMENT_DETAILS: "/get-stock-adjustment-details",
    GET_PRODUCT_LIST_FOR_ADJUSTMENT: "/get-product-list-for-adjustment",
    CREATE_STOCK_ADJUSTMENT: "/create-stock-adjustment",
    UPDATE_STOCK_ADJUSTMENT: "/update-stock-adjustment",
    VERIFY_STOCK_ADJUSTMENT: "/verify-stock-adjustment",
    REJECT_STOCK_ADJUSTMENT: "/reject-stock-adjustment",
    CANCEL_STOCK_ADJUSTMENT: "/cancel-stock-adjustment",
    GENERATE_STOCK_ADJUSTMENT_REPORT: "/generate-stock-adjustment-report",

    CHANGE_PASSWORD: "/change-user-password",
    VERIFY_OTP_FOR_PASSWORD_CHANGE: "/verify-otp-for-password-change",

    GET_PROFILE_INFO: "/get-profile-info",

    GET_ACTIVITY_LOG_LIST: "/get-activity-log-list",

    GET_PURCHASE_ORDER_REPORT: "/get-purchase-order-report",
    GET_PURCHASE_ORDER_PRODUCTS_REPORT: "/get-purchase-order-products-report",

    // Notes
    GET_USER_NOTE_LIST: "/get-note-list",
    GET_USER_NOTE_DETAILS: "/get-note-details",
    CREATE_USER_NOTE: "/create-note",
    UPDATE_USER_NOTE: "/update-note",
    DELETE_USER_NOTE: "/delete-note/:oid",

    // Analytics
    GET_CONFIGURATION_ANALYTICS: "/get-configuration-analytics",

    // Customers and locations
    GET_CUSTOMER_LIST: "/get-customer-list",
    GET_CUSTOMER_DETAILS: "/get-customer-details",
    FIND_CUSTOMER_BY_PHONE: "/find-customer-by-phone",
    CREATE_CUSTOMER: "/create-customer",
    UPDATE_CUSTOMER_DETAILS: "/update-customer-details",
    FLAG_CUSTOMER: "/flag-customer",
    CREATE_CUSTOMER_ADDRESS: "/create-customer-address",
    UPDATE_CUSTOMER_ADDRESS: "/update-customer-address",
    RETIRE_CUSTOMER_ADDRESS: "/retire-customer-address",
    GENERATE_CUSTOMER_LIST_REPORT: "/generate-customer-list-report",
    SEARCH_LOCATION: "/search-location",
    MATCH_LOCATION: "/match-location",
    UPDATE_DELIVERY_CHARGES: "/update-delivery-charges",
    GET_SETTINGS: "/get-settings",
    UPDATE_SETTINGS: "/update-settings",
  },
  IMAGE_FILE_UPLOAD_TYPE: ["photo", "report"],
};
